// Global language catalogue — BCP 47 codes, native names, RTL flags.
// interface: true = full hand-reviewed UI dictionary available (others fall back to English).
export const LANGUAGES = [
  { code: "es", native: "Español", rtl: false, interface: true },
  { code: "en", native: "English", rtl: false, interface: true },
  { code: "fr", native: "Français", rtl: false, interface: true },
  { code: "ar", native: "العربية", rtl: true, interface: true },
  { code: "eu", native: "Euskara", rtl: false },
  { code: "ca", native: "Català", rtl: false },
  { code: "gl", native: "Galego", rtl: false },
  { code: "pt", native: "Português", rtl: false },
  { code: "pt-BR", native: "Português (Brasil)", rtl: false },
  { code: "it", native: "Italiano", rtl: false },
  { code: "de", native: "Deutsch", rtl: false },
  { code: "nl", native: "Nederlands", rtl: false },
  { code: "ro", native: "Română", rtl: false },
  { code: "pl", native: "Polski", rtl: false },
  { code: "uk", native: "Українська", rtl: false },
  { code: "ru", native: "Русский", rtl: false },
  { code: "fa", native: "فارسی", rtl: true },
  { code: "ps", native: "پښتو", rtl: true },
  { code: "ur", native: "اردو", rtl: true },
  { code: "he", native: "עברית", rtl: true },
  { code: "ku", native: "کوردی", rtl: true },
  { code: "tr", native: "Türkçe", rtl: false },
  { code: "hi", native: "हिन्दी", rtl: false },
  { code: "bn", native: "বাংলা", rtl: false },
  { code: "pa", native: "ਪੰਜਾਬੀ", rtl: false },
  { code: "ta", native: "தமிழ்", rtl: false },
  { code: "te", native: "తెలుగు", rtl: false },
  { code: "ml", native: "മലയാളം", rtl: false },
  { code: "gu", native: "ગુજરાતી", rtl: false },
  { code: "mr", native: "मराठी", rtl: false },
  { code: "ne", native: "नेपाली", rtl: false },
  { code: "si", native: "සිංහල", rtl: false },
  { code: "zh-Hans", native: "中文（简体）", rtl: false },
  { code: "zh-Hant", native: "中文（繁體）", rtl: false },
  { code: "yue", native: "粵語", rtl: false },
  { code: "ja", native: "日本語", rtl: false },
  { code: "ko", native: "한국어", rtl: false },
  { code: "vi", native: "Tiếng Việt", rtl: false },
  { code: "th", native: "ไทย", rtl: false },
  { code: "id", native: "Bahasa Indonesia", rtl: false },
  { code: "ms", native: "Bahasa Melayu", rtl: false },
  { code: "fil", native: "Filipino", rtl: false },
  { code: "km", native: "ខ្មែរ", rtl: false },
  { code: "my", native: "မြန်မာ", rtl: false },
  { code: "kk", native: "Қазақша", rtl: false },
  { code: "uz", native: "Oʻzbekcha", rtl: false },
  { code: "sw", native: "Kiswahili", rtl: false },
  { code: "so", native: "Soomaali", rtl: false },
  { code: "am", native: "አማርኛ", rtl: false },
  { code: "ti", native: "ትግርኛ", rtl: false },
  { code: "ha", native: "Hausa", rtl: false },
  { code: "yo", native: "Yorùbá", rtl: false },
  { code: "ig", native: "Igbo", rtl: false },
  { code: "ht", native: "Kreyòl Ayisyen", rtl: false },
  { code: "qu", native: "Runasimi", rtl: false },
  { code: "gn", native: "Avañe'ẽ", rtl: false }
];

export const getLanguage = (code) => LANGUAGES.find((l) => l.code === code) || LANGUAGES[1];